---
- name: Update Raspberry Pi Nodes
  hosts: all
  become: yes
  tasks:
    - name: Ping
      ping:

    - name: apt-get update
      apt:
        update_cache: yes

    - name: Upgrade all
      apt:
        upgrade: dist

